name: FORD

on:
  push:
  pull_request:
    types: [opened, synchronize]

env:
  LANG: "en_US.UTF-8"
  LC_ALL: "en_US.UTF-8"
  NCPU: "2"
  HOMEBREW_DISPLAY_INSTALL_TIMES: "ON" # Benchmark Homebrew install times
  HOMEBREW_NO_ANALYTICS: "ON" # These speed up homebrew installs
  HOMEBREW_NO_AUTO_UPDATE: "ON"
  HOMEBREW_NO_BOTTLE_SOURCE_FALLBACK: "ON"
  HOMEBREW_NO_GITHUB_API: "ON"
  HOMEBREW_NO_INSTALL_CLEANUP: "ON"
  PIP_DISABLE_PIP_VERSION_CHECK: "ON" # These speed up installs from pip
  PIP_NO_CLEAN: "ON"
  PIP_PREFER_BINARY: "ON"
  TZ: "UTC"
  GCC_V: 8

jobs:
  Build-API-Docs:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: false
      - name: set outputs
        id: so
        run: |
          echo "::set-output name=homedir::${HOME}"
          if brew --cache ; then
            rm -rf $(brew --cache)
            echo "::set-output name=homebrew_cache::$(brew --cache)"
          fi
      - uses: actions/cache@v1
        with:
          path: ${{ steps.so.outputs.homebrew_cache }}
          key: ${{ runner.os }}-brew-ford-cache
      - name: Install packages
        run: |
          pip3 install --prefer-binary --no-clean --disable-pip-version-check --prefer-binary --progress-bar off lxml
          brew install -f --force-bottle --keep-tmp ford gcc@8
          type -a ford
          ford --version
      - name: Build documentation
        id: build-documentation
        run: |
          mkdir -p $(brew --cache) || true
          ford -r $(git describe --always) --debug API-doc-FORD-file.md
          touch API-doc/.nojekyll
          zip -vr API-docs.zip API-doc/ -x "*.DS_Store"
      - name: Upload Documentation
        uses: actions/upload-artifact@v1
        with:
          name: FORD-API-docs
          path: ./API-docs.zip

  Check-Links:
    runs-on: ubuntu-latest
    needs: Build-API-Docs
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: false
      - name: Get Documentation
        uses: actions/download-artifact@v1
        with:
          name: FORD-API-docs
          path: ./API-doc
      - name: set git vars
        id: sgv
        run: |
          echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"
          echo "::set-output name=branch::${GITHUB_REF##*/}"
      - name: Check Links
        uses: peter-evans/link-checker@v1
        id: lc
        with:
          args: -c 5 -v -r -x (gsellc\.com$)|(github\.com\/cmacmackin\/ford$)|(gcc\.gnu\.org\/onlinedocs\/gfortran)|(\/interface\/operator) API-doc
      - name: Prune OK links
        id: pol
        if: steps.lc.outputs.exit_code != 0
        shell: bash
        run: |
          echo "ping @${{github.actor}}" >> issue.md
          echo "On commit: ${GITHUB_SHA}" >> issue.md
          echo "" >> issue.md
          sed '/^[[:space:]]*OK[[:space:]]*/d' ./link-checker/out.md >> issue.md
          pr_msg=$(<issue.md)
          pr_msg="${pr_msg//'%'/'%25'}"
          pr_msg="${pr_msg//$'\n'/'%0A'}"
          pr_msg="${pr_msg//$'\r'/'%0D'}"
          echo "::set-output name=pr_msg::$pr_msg"
      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v2
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop' || endsWith( github.ref , '-dev' ) )
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title:  "Broken links: ATTN @${{github.actor}} ${{ steps.sgv.outputs.branch }}@${{ steps.sgv.outputs.short_sha }}"
          content-filepath: ./issue.md
          labels: report, automated issue, documentation
          assignees: ${{ github.actor }}
      - name: Comment PR when failed
        uses: mshick/add-pr-comment@v1
        if: steps.lc.outputs.exit_code != 0 && github.event_name == 'pull_request'
        with:
          message: "${{ steps.pol.outputs.pr_msg }}"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy API Docs
        uses: docker://peaceiris/gh-pages:v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./API-doc
        with:
          emptyCommits: false
          forceOrphan: true
          commitMessage: ${{ github.event.head_commit.message }}
          username: ${{ github.actor }}
        if: success() && github.event_name == 'push' && github.ref == 'refs/heads/master'
      - name: Fail on broken links
        run: |
          echo "Ref: ${{ github.ref }}"
          echo "Event: ${{ github.event_name }}"
          exit ${{ steps.lc.outputs.exit_code }}
