on:
  schedule:
  - cron: 49 7 * * *
name: Nightly-mirror
jobs:
  mirrorWiki:
    name: Mirror wiki
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Mirror wiki
      uses: docker://buildpack-deps:testing-scm
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        IBB_PWLESS_DEPLOY_KEY: ${{ secrets.IBB_PWLESS_DEPLOY_KEY }}
        MIRROR_WIKI: ${{ secrets.MIRROR_WIKI }}.wiki.git
        SOURCE_WIKI: git@github.com:sourceryinstitute/MORFEUS-Source.wiki.git
      with:
        entrypoint: .github/workflows/wiki-update.sh
    - name: Mirror to repo
      uses: docker://buildpack-deps:testing-scm
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        IBB_PWLESS_DEPLOY_KEY: ${{ secrets.IBB_PWLESS_DEPLOY_KEY }}
        MIRROR_URL: ${{ secrets.MIRROR_URL }}.git
      with:
        entrypoint: .github/workflows/main.sh
